### ISSUE TITLE
#51 Input Requirements (Frontend)

### ISSUE THREAD

**Issue by Y4nnikH** [BP-WiSe21-22-Gruppe-52/BP-frontend#167]
Als Admin möchte ich die Länge der Inputs sowie erlaubte Characters für Nutzername, Motivation, etc einschränken, um Fehler im Backend zu verhindern.

Akzeptanzkriterium: Die Länge der Nutzernamen etc ist im Backend sinnvoll beschränkt.Eingaben werden im Frontend beschränkt, sodass die im Backend definierten Begrenzungen eingehalten werden.

Aufwand: 2 Story Points.

**Comment by Y4nnikH** [comment]
This is done, yes?

**Comment by Laennart** [comment]
> This is done, yes?

Yes.
